BEGIN TRANSACTION;
DROP TABLE IF EXISTS "meals";
CREATE TABLE IF NOT EXISTS "meals" (
	"meal_id"	INTEGER,
	"category"	TEXT NOT NULL,
	"meal"	TEXT NOT NULL,
	PRIMARY KEY("meal_id" AUTOINCREMENT)
);
DROP TABLE IF EXISTS "ingredients";
CREATE TABLE IF NOT EXISTS "ingredients" (
	"ingredient_id"	INTEGER,
	"meal_id"	INTEGER NOT NULL,
	"ingredient"	TEXT NOT NULL,
	FOREIGN KEY("meal_id") REFERENCES "meals"("meal_id"),
	FOREIGN KEY("meal_id") REFERENCES "meals"("meal_id"),
	PRIMARY KEY("ingredient_id" AUTOINCREMENT)
);
INSERT INTO "meals" ("meal_id","category","meal") VALUES (1,'breakfast','crambled eggs'),
 (2,'breakfast','sandwich'),
 (3,'breakfast','oatmeal'),
 (4,'breakfast','english breakfast'),
 (5,'lunch','sushi'),
 (6,'lunch','chicken salad'),
 (7,'lunch','omelette'),
 (8,'lunch','salad'),
 (9,'dinner','pumpkin soup'),
 (10,'dinner','beef steak'),
 (11,'dinner','pizza'),
 (12,'dinner','tomato soup');
INSERT INTO "ingredients" ("ingredient_id","meal_id","ingredient") VALUES (1,1,'eggs'),
 (2,1,'milk'),
 (3,1,'cheese'),
 (4,2,'bread'),
 (5,2,'cheese'),
 (6,2,'ham'),
 (7,3,'oats'),
 (8,3,'milk'),
 (9,3,'banana'),
 (10,3,'peanut butter'),
 (11,4,'eggs'),
 (12,4,'sausages'),
 (13,4,'bacon'),
 (14,4,'tomatoes'),
 (15,4,'bread'),
 (16,5,'salmon'),
 (17,5,'rice'),
 (18,5,'avocado'),
 (19,6,'chicken'),
 (20,6,'lettuce'),
 (21,6,'tomato'),
 (22,6,'olives'),
 (23,7,'eggs'),
 (24,7,'milk'),
 (25,7,'cheese'),
 (26,8,'lettuce'),
 (27,8,'tomato'),
 (28,8,'onion'),
 (29,8,'cheese'),
 (30,8,'olives'),
 (31,9,'pumpkin'),
 (32,9,'coconut milk'),
 (33,9,'curry'),
 (34,9,'carrots'),
 (35,10,'beef steak'),
 (36,11,'flour'),
 (37,11,'tomato'),
 (38,11,'cheese'),
 (39,11,'salami'),
 (40,11,'tomato'),
 (41,11,'orzo');
COMMIT;
